import type {
  ActivityItem,
  AuditLog,
  CalendarEvent,
  Customer,
  DashboardData,
  Deal,
  NotificationItem,
  Profile,
  ReportCard,
  SegmentPerformance,
  SettingsState,
  Task,
  TeamMember,
  User,
} from "@/types";

export const currentUser: User = {
  id: "u_1",
  name: "Alicia Morgan",
  email: "alicia@matrixcrm.io",
  role: "Admin",
  avatar: "AM",
  title: "VP Revenue Operations",
};

export const customers: Customer[] = [
  {
    id: "cus_001",
    company: "Northstar Labs",
    industry: "Biotech",
    owner: "Mia Turner",
    email: "ops@northstarlabs.com",
    status: "Active",
    health: "Healthy",
    plan: "Enterprise",
    region: "North America",
    segment: "Strategic",
    mrr: 28000,
    arr: 336000,
    createdAt: "2026-01-12",
    renewalDate: "2026-11-20",
    contacts: 8,
    openDeals: 2,
    notes:
      "Expanding from analytics to workflow automation. Strong executive sponsorship.",
  },
  {
    id: "cus_002",
    company: "Silverline Health",
    industry: "Healthcare",
    owner: "Jacob Lee",
    email: "finance@silverline.health",
    status: "At risk",
    health: "Needs attention",
    plan: "Growth",
    region: "Europe",
    segment: "Commercial",
    mrr: 9200,
    arr: 110400,
    createdAt: "2026-02-04",
    renewalDate: "2026-08-16",
    contacts: 4,
    openDeals: 1,
    notes:
      "Renewal depends on security review and migration timeline confidence.",
  },
  {
    id: "cus_003",
    company: "Futura Mobility",
    industry: "Mobility",
    owner: "Nina Patel",
    email: "hello@futuramobility.com",
    status: "Lead",
    health: "Healthy",
    plan: "Starter",
    region: "North America",
    segment: "SMB",
    mrr: 1800,
    arr: 21600,
    createdAt: "2026-04-20",
    renewalDate: "2027-04-20",
    contacts: 2,
    openDeals: 1,
    notes: "Inbound lead from product-led growth funnel.",
  },
  {
    id: "cus_004",
    company: "Atlas Commerce",
    industry: "Retail",
    owner: "Oliver Chen",
    email: "growth@atlascommerce.com",
    status: "Active",
    health: "Healthy",
    plan: "Growth",
    region: "APAC",
    segment: "Commercial",
    mrr: 14600,
    arr: 175200,
    createdAt: "2026-03-11",
    renewalDate: "2027-03-11",
    contacts: 6,
    openDeals: 3,
    notes: "Interested in omnichannel lifecycle reporting.",
  },
  {
    id: "cus_005",
    company: "Bluepeak Energy",
    industry: "Energy",
    owner: "Lila Grant",
    email: "team@bluepeak.energy",
    status: "Lead",
    health: "Healthy",
    plan: "Starter",
    region: "Europe",
    segment: "SMB",
    mrr: 2400,
    arr: 28800,
    createdAt: "2026-03-28",
    renewalDate: "2027-03-28",
    contacts: 3,
    openDeals: 1,
    notes: "Exploring forecasting and field-service workflow sync.",
  },
  {
    id: "cus_006",
    company: "Summit AI",
    industry: "Software",
    owner: "Ethan Wells",
    email: "contact@summitai.io",
    status: "Active",
    health: "Critical",
    plan: "Enterprise",
    region: "North America",
    segment: "Strategic",
    mrr: 32000,
    arr: 384000,
    createdAt: "2026-05-03",
    renewalDate: "2026-09-12",
    contacts: 9,
    openDeals: 2,
    notes: "Open escalation on SSO provisioning; executive sponsor engaged.",
  },
];

export const deals: Deal[] = [
  {
    id: "deal_001",
    name: "Northstar expansion pack",
    customerId: "cus_001",
    customerName: "Northstar Labs",
    owner: "Mia Turner",
    stage: "Negotiation",
    value: 148000,
    probability: 72,
    expectedClose: "2026-06-14",
    source: "Customer success",
    nextStep: "Finalize data residency appendix",
    updatedAt: "2026-05-18T13:20:00Z",
  },
  {
    id: "deal_002",
    name: "Atlas APAC seat expansion",
    customerId: "cus_004",
    customerName: "Atlas Commerce",
    owner: "Oliver Chen",
    stage: "Proposal",
    value: 76000,
    probability: 54,
    expectedClose: "2026-06-28",
    source: "Upsell",
    nextStep: "Share board-ready business case",
    updatedAt: "2026-05-18T09:15:00Z",
  },
  {
    id: "deal_003",
    name: "Silverline renewal stabilization",
    customerId: "cus_002",
    customerName: "Silverline Health",
    owner: "Jacob Lee",
    stage: "Legal",
    value: 118000,
    probability: 61,
    expectedClose: "2026-05-29",
    source: "Renewal",
    nextStep: "Complete security packet",
    updatedAt: "2026-05-17T17:05:00Z",
  },
  {
    id: "deal_004",
    name: "Bluepeak first enterprise pilot",
    customerId: "cus_005",
    customerName: "Bluepeak Energy",
    owner: "Lila Grant",
    stage: "Discovery",
    value: 34000,
    probability: 28,
    expectedClose: "2026-07-12",
    source: "Partner referral",
    nextStep: "Run process mapping workshop",
    updatedAt: "2026-05-16T12:40:00Z",
  },
  {
    id: "deal_005",
    name: "Summit AI platform rescue",
    customerId: "cus_006",
    customerName: "Summit AI",
    owner: "Ethan Wells",
    stage: "Proposal",
    value: 92000,
    probability: 43,
    expectedClose: "2026-06-10",
    source: "Risk mitigation",
    nextStep: "Present stabilization roadmap",
    updatedAt: "2026-05-18T20:12:00Z",
  },
];

export const tasks: Task[] = [
  {
    id: "task_001",
    title: "Prepare Northstar pricing addendum",
    account: "Northstar Labs",
    assignee: "Mia Turner",
    dueDate: "2026-05-20",
    priority: "High",
    status: "In progress",
    type: "Renewal",
  },
  {
    id: "task_002",
    title: "Review Silverline security questionnaire",
    account: "Silverline Health",
    assignee: "Jacob Lee",
    dueDate: "2026-05-21",
    priority: "Critical",
    status: "Blocked",
    type: "Implementation",
  },
  {
    id: "task_003",
    title: "Schedule Atlas executive checkpoint",
    account: "Atlas Commerce",
    assignee: "Oliver Chen",
    dueDate: "2026-05-22",
    priority: "Medium",
    status: "Open",
    type: "Follow-up",
  },
  {
    id: "task_004",
    title: "Publish board report draft",
    account: "Internal",
    assignee: "Alicia Morgan",
    dueDate: "2026-05-23",
    priority: "High",
    status: "Open",
    type: "Internal",
  },
  {
    id: "task_005",
    title: "Finalize Summit AI recovery plan",
    account: "Summit AI",
    assignee: "Ethan Wells",
    dueDate: "2026-05-20",
    priority: "Critical",
    status: "In progress",
    type: "Renewal",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "evt_001",
    title: "Northstar commercial review",
    owner: "Mia Turner",
    customer: "Northstar Labs",
    start: "2026-05-20T14:00:00Z",
    end: "2026-05-20T15:00:00Z",
    location: "Zoom",
    type: "Review",
  },
  {
    id: "evt_002",
    title: "Atlas growth workshop",
    owner: "Oliver Chen",
    customer: "Atlas Commerce",
    start: "2026-05-21T09:00:00Z",
    end: "2026-05-21T10:30:00Z",
    location: "Singapore office",
    type: "Meeting",
  },
  {
    id: "evt_003",
    title: "Pipeline forecast prep",
    owner: "Alicia Morgan",
    start: "2026-05-22T16:00:00Z",
    end: "2026-05-22T17:00:00Z",
    location: "Board room",
    type: "Reminder",
  },
  {
    id: "evt_004",
    title: "Bluepeak product demo",
    owner: "Lila Grant",
    customer: "Bluepeak Energy",
    start: "2026-05-23T13:00:00Z",
    end: "2026-05-23T14:00:00Z",
    location: "Zoom",
    type: "Demo",
  },
];

export const teamMembers: TeamMember[] = [
  {
    id: "tm_001",
    name: "Alicia Morgan",
    email: "alicia@matrixcrm.io",
    role: "Admin",
    region: "North America",
    quota: 2400000,
    attainment: 83,
    status: "Available",
    avatar: "AM",
  },
  {
    id: "tm_002",
    name: "Mia Turner",
    email: "mia@matrixcrm.io",
    role: "Sales",
    region: "North America",
    quota: 1200000,
    attainment: 91,
    status: "In meeting",
    avatar: "MT",
  },
  {
    id: "tm_003",
    name: "Jacob Lee",
    email: "jacob@matrixcrm.io",
    role: "Customer Success",
    region: "Europe",
    quota: 900000,
    attainment: 74,
    status: "Available",
    avatar: "JL",
  },
  {
    id: "tm_004",
    name: "Oliver Chen",
    email: "oliver@matrixcrm.io",
    role: "Manager",
    region: "APAC",
    quota: 1050000,
    attainment: 88,
    status: "Out of office",
    avatar: "OC",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "ntf_001",
    title: "Forecast locked for weekly review",
    description: "Revenue forecast snapshot has been published to leadership.",
    timestamp: "2026-05-19T08:00:00Z",
    type: "Info",
    read: false,
  },
  {
    id: "ntf_002",
    title: "Security escalation acknowledged",
    description:
      "Summit AI incident channel updated with ETA from engineering.",
    timestamp: "2026-05-19T07:10:00Z",
    type: "Security",
    read: false,
  },
  {
    id: "ntf_003",
    title: "Northstar expansion approved",
    description: "Procurement confirmed budget availability for Q3 rollout.",
    timestamp: "2026-05-18T19:30:00Z",
    type: "Success",
    read: true,
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "log_001",
    actor: "Alicia Morgan",
    action: "Changed deal approval mode",
    target: "Workspace settings",
    timestamp: "2026-05-19T08:42:00Z",
    ipAddress: "10.24.1.88",
    severity: "Medium",
  },
  {
    id: "log_002",
    actor: "Jacob Lee",
    action: "Exported customer health report",
    target: "Reports",
    timestamp: "2026-05-18T17:16:00Z",
    ipAddress: "10.24.1.43",
    severity: "Low",
  },
  {
    id: "log_003",
    actor: "System",
    action: "Blocked suspicious login attempt",
    target: "Alicia Morgan",
    timestamp: "2026-05-18T05:11:00Z",
    ipAddress: "185.112.41.7",
    severity: "High",
  },
];

export const reportCards: ReportCard[] = [
  {
    id: "rep_001",
    title: "Retention",
    value: "94.8%",
    change: "+1.9%",
    trend: "up",
  },
  {
    id: "rep_002",
    title: "Net expansion",
    value: "118%",
    change: "+4.1%",
    trend: "up",
  },
  {
    id: "rep_003",
    title: "Average cycle",
    value: "31 days",
    change: "-3.6%",
    trend: "down",
  },
];

export const segmentPerformance: SegmentPerformance[] = [
  { segment: "Strategic", retention: 97, expansion: 24, pipeline: 780000 },
  { segment: "Commercial", retention: 93, expansion: 16, pipeline: 420000 },
  { segment: "SMB", retention: 90, expansion: 9, pipeline: 140000 },
];

export const recentActivity: ActivityItem[] = [
  {
    id: "act_001",
    title: "Deal moved to negotiation",
    description: "Northstar expansion progressed after pricing review.",
    timestamp: "2026-05-19T09:10:00Z",
    actor: "Mia Turner",
    type: "Deal",
  },
  {
    id: "act_002",
    title: "Critical task opened",
    description: "Security packet for Silverline renewal needs exec review.",
    timestamp: "2026-05-19T08:22:00Z",
    actor: "Jacob Lee",
    type: "Task",
  },
  {
    id: "act_003",
    title: "Customer health downgraded",
    description: "Summit AI moved to critical due to unresolved SSO issues.",
    timestamp: "2026-05-18T20:15:00Z",
    actor: "Ethan Wells",
    type: "Customer",
  },
];

export const profile: Profile = {
  id: "profile_001",
  name: "Alicia Morgan",
  email: "alicia@matrixcrm.io",
  title: "VP Revenue Operations",
  phone: "+1 (415) 555-0199",
  timezone: "America/Los_Angeles",
  bio: "Operating partner for revenue, customer success, and strategic planning.",
  avatar: "AM",
};

export const settings: SettingsState = {
  companyName: "Matrix Cloud",
  workspaceId: "matrix-cloud-prod",
  securityAlerts: true,
  weeklyDigest: true,
  autoAssignOwners: false,
  dealApprovalMode: "Manager",
  theme: "Light",
};

export function getDashboardData(): DashboardData {
  return {
    metrics: [
      { label: "Net revenue", value: "$284K", delta: "+12.4%", trend: "up" },
      { label: "Active deals", value: "18", delta: "+3.1%", trend: "up" },
      { label: "New customers", value: "26", delta: "+8.9%", trend: "up" },
      { label: "Conversion rate", value: "31.8%", delta: "+1.2%", trend: "up" },
    ],
    salesSeries: [
      { name: "Jan", revenue: 84, pipeline: 110 },
      { name: "Feb", revenue: 91, pipeline: 124 },
      { name: "Mar", revenue: 105, pipeline: 132 },
      { name: "Apr", revenue: 112, pipeline: 138 },
      { name: "May", revenue: 126, pipeline: 160 },
      { name: "Jun", revenue: 141, pipeline: 182 },
    ],
    quickActions: [
      {
        id: "qa_001",
        title: "Create customer",
        description: "Open a new account and assign an owner.",
        href: "/customers",
      },
      {
        id: "qa_002",
        title: "Review blocked tasks",
        description: "Resolve blockers before weekly forecast.",
        href: "/tasks",
      },
      {
        id: "qa_003",
        title: "Open reports",
        description: "Share KPI snapshots with leadership.",
        href: "/reports",
      },
    ],
    recentActivity,
    upcomingTasks: tasks.slice(0, 4),
    activeDeals: deals.slice(0, 4),
  };
}
